#!/bin/bash
#PBS -P xf1
#PBS -q express
#PBS -l walltime=01:00:00
#PBS -l mem=32GB
#PBS -l ncpus=16
#PBS -l wd
#PBS -l jobfs=20GB

module load ngmap
module load samtools/1.4

ngm -t ${PBS_NCPUS} -r ${REF} -1 ${R1} -2 ${R2} \
 --rg-id ${RGSM} --rg-sm ${RGSM} --rg-lb ${RGLB} --rg-pl ${RGPL} --rg-pu ${RGPU} | \
samtools view -h - | \
samtools sort --threads 8 -m 2G - -o ${PBS_JOBFS}/$(basename $R1).bam -O BAM

cp $PBS_JOBFS/$(basename $R1).bam ${BAMDIR}/${RGSM}.bam
