#!/bin/bash
#PBS -P xf1
#PBS -q express
#PBS -l walltime=01:00:00
#PBS -l mem=32GB
#PBS -l ncpus=8
#PBS -l wd
#PBS -l jobfs=20GB


module load java

INDIR=$(dirname $BAM)
FNAME=$(basename "$BAM" .bam)

java -Xmx14G -jar ~/apps/bin/picard.jar MarkDuplicates I=${BAM} O=${PBS_JOBFS}/${FNAME}.dedup.bam \
 METRICS_FILE=${OUTDIR}/${FNAME}.metrics.txt MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 TMP_DIR=${PBS_JOBFS}


cp ${PBS_JOBFS}/${FNAME}.dedup.bam ${OUTDIR}/${FNAME}.dedup.bam
